export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_MEAL_BEGIN = "CREATE_MEAL_BEGIN";
export const CREATE_MEAL_SUCCESS = "CREATE_MEAL_SUCCESS";
export const CREATE_MEAL_ERROR = "CREATE_MEAL_ERROR";

export const GET_MEALS_BEGIN = "GET_MEALS_BEGIN";
export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS";

export const GET_GLUCOSE_BEGIN = "GET_GLUCOSE_BEGIN";
export const GET_GLUCOSE_SUCCESS = "GET_GLUCOSE_SUCCESS";

export const SET_EDIT_MEAL = "SET_EDIT_MEAL";

export const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN";

export const EDIT_MEAL_BEGIN = "EDIT_MEAL_BEGIN";
export const EDIT_MEAL_SUCCESS = "EDIT_MEAL_SUCCESS";
export const EDIT_MEAL_ERROR = "EDIT_MEAL_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";
